### PR TITLE
Implemented a prototype for the smart pin

### PR DESCRIPTION
**Pull request by Youssef-Beltagy**
This is the first iteration of the "smart-pin." 

I used esp32 with the Arduino framework. I used PlatformIO through Visual Studio Code.

Currently, the smart pin tracks the temperature and humidity and has two dummy characteristics. The current "Smart-Pin" sits and waits for read requests.

We may want to comment this more or build the "smart-pin" from the same Microcontroller as the inhaler later.

### CODE REVIEW

**Comment by Youssef-Beltagy** [comment]
I used the DHT11 temperature and humidity sensor. You can get it from [here](https://www.adafruit.com/product/386)

I changed the implementation of the smart-pin so it no longer notifies. Right now, it simply sits and waits for read requests. But now I added two dummy characteristics.

The pin now send the temperature and humidity information as character array instead of a single byte.

**Review by jenlee1919 — APPROVED** [review]

**Comment by jenlee1919** [comment]
How did you power the smart pin?

**Comment by Youssef-Beltagy** [comment]
> How did you power the smart pin?

That is a good question.

I used a development board for the esp32. You can get a similar one [here](https://www.amazon.com/Espressif-ESP32-DevKitC-32UE-Development-Board/dp/B087T94ZH9). There are a lot of variants of these boards with minimal difference between.

You can power this board through its USB port.

**Review by SarahPanther — APPROVED** [review]
You may want to add comments for the DigitCharacteristic and AlphabetCharacteristic to let future coders know that they are just dummy characteristics and should be replaced in the future.

**Pull request merged**
